### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xingchen020622** [zituitui/BELM#9]
Could you please tell me if there is a folder called , or where I can download it from?xxxxx/stable-diffusion-v1-5

**Comment by zituitui** [comment]
hi
you can download from
https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5

**Comment by xingchen020622** [comment]
Thank you!But Why did this problem occur after I downloaded it manually?D:\aconda\envs\DL\lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
Traceback (most recent call last):
  File "./scripts/reconstruction.py", line 150, in <module>
    main()
  File "./scripts/reconstruction.py", line 128, in main
    sd = StableDiffusionPipeline.from_pretrained(r"C:\Users\Windows\Desktop\papers\BELM-main\models--stable-diffusion-v1-5--stable-diffusion-v1-5", torch_dtype=dtype)
  File "D:\aconda\envs\DL\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\aconda\envs\DL\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 760, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "D:\aconda\envs\DL\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\aconda\envs\DL\lib\site-packages\diffusers\configuration_utils.py", line 373, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory C:\Users\Windows\Desktop\papers\BELM-main\models--stable-diffusion-v1-5--stable-diffusion-v1-5.

**Comment by zituitui** [comment]
you should point to the root folder of the downloaded [/stable-diffusion-v1-5](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5).

And I run this on Linux, not Windows, maybe some os-related code should be altered.

**Comment by xingchen020622** [comment]
Thank you !!!Can I experiment with Stable Diffusion XL (SDXL) and Stable Diffusion 3.5 (SD3.5)? What parameters do I need to adjust? I’ve noticed that BELM cannot perfectly invert an image, and there are some unrealistic aspects.
